import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { FlatCompat } from '@eslint/eslintrc'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const compat = new FlatCompat({ baseDirectory: __dirname })

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript', 'prettier'),
  {
    rules: {
      // CLAUDE.md §1 — TypeScript strict, no `any`.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    /*
     * .cjs is CommonJS by definition, so require() is the correct call there,
     * not a lapse. These are the Windows service install/uninstall scripts for
     * the print agent, which node-windows runs directly.
     *
     * This came to light because the lint step was not actually running: pnpm
     * had stopped exposing eslint-config-next's plugins, and `next build`
     * reports that failure and then exits 0 anyway. See .npmrc.
     */
    files: ['**/*.cjs'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    // next-env.d.ts is generated by Next and uses triple-slash references.
    ignores: ['.next/**', 'node_modules/**', 'next-env.d.ts', 'types/database.ts'],
  },
]

export default config
