/**
 * PLACEHOLDER — replaced in Prompt 05.
 *
 * Generated by `supabase gen types typescript` once the migrations in
 * supabase/migrations/ have been applied. Do not hand-edit after that point:
 * CLAUDE.md §13.2 requires regeneration after every migration.
 */
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
    CompositeTypes: Record<string, never>
  }
}
