import type { Metadata, Viewport } from 'next'
import { Fraunces, Inter } from 'next/font/google'
import './globals.css'

/**
 * Kiosk headings: a warm display serif (§1). Fraunces at a low optical size and
 * modest softness reads warm and considered at 64px without turning decorative.
 */
const fraunces = Fraunces({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-fraunces',
  axes: ['SOFT', 'WONK', 'opsz'],
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'All India Café',
  description: 'Customer Experience Intelligence System',

  // Installed-app metadata. The manifest is generated by app/manifest.ts and
  // linked automatically; these are the bits iOS still reads from meta tags
  // because it has never supported the manifest properly.
  appleWebApp: {
    capable: true,
    title: 'Feedback',
    // The kiosk paints its own ivory ground; a translucent bar would show the
    // page scrolling under the clock.
    statusBarStyle: 'default',
  },

  // Guests do not link to a kiosk, and neither should a search engine.
  robots: { index: false, follow: false },

  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: '/icons/apple-touch-icon.png',
  },
}

/**
 * Viewport, separated from metadata because Next 15 wants it that way.
 *
 * `viewportFit: 'cover'` matters on a phone-shaped install: without it the
 * full-bleed artwork stops at the safe area and leaves bars top and bottom.
 * `userScalable: false` is §6's no-zoom rule — a guest pinching a kiosk screen
 * has broken the layout and has no way back.
 */
export const viewport: Viewport = {
  themeColor: '#0f5132',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: 'cover',
}

/**
 * Root layout — deliberately bare.
 *
 * The kiosk and the admin app share tokens and nothing else: chrome and layout
 * belong to `app/(kiosk)/layout.tsx` and `app/(admin)/admin/layout.tsx`.
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${fraunces.variable} ${inter.variable}`}>
      <body>{children}</body>
    </html>
  )
}
